# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 225b4691666f10990bcd3f66907903efba0821b9ca089c23219727bd83ad8340a003d2d74ec1fdabdf6318331a07fbbcd04e35599cf71f1c4456cf62cea6b3f3

test:
  secret_key_base: 0e806b2ec8b2c45e7b5ec820d9d3968a2466a521fc7b639260ceb65c044962f8c1676e6f716660034c9ab7d4492105e2c8bddfd5914331ad16068a15b692cca2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
